### ISSUE TITLE
Demo site is offline

### ISSUE THREAD

**Issue by vitorhsb** [gauntface/web-push-book#120]
## Type of Issue
> Demo site is offline

cc @gauntface

## Details....
> The demo site is offline. This has been working as wonderful documentation resource, it would be great to have it online again.

![image](https://user-images.githubusercontent.com/86801/81925061-e3c3f900-95d7-11ea-939f-626f8570ced9.png)

**Comment by gauntface** [comment]
Sorry I had to update hosts, but should be good now: https://web-push-book.gauntface.com/demos/notification-examples/
