### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by roshin-8** [gauntface/web-push-book#32]
I've followed the steps to run site locally but I need to set up the demos
I did rvm . do bundle install
Now what?

**Comment by gauntface** [comment]
Apologies, I should document this better.

The demo should be runnable with:

    git clone https://github.com/gauntface/web-push-book.git
    cd web-push-book
    npm install
    cd src/demos/node-server/
    node index.js

Let me know if that works for you.

The RVM bundle etc is more to do with the building and running of the book itself.
