### ISSUE TITLE
Placement of next arrow

### ISSUE THREAD

**Issue by bkazi** [gauntface/web-push-book#38]
The button for the next page falls out of the normal viewport for me (screenshot included). Was wondering if it's just my browser somehow or if it's even an actual issue
![screenshot_20170204-153141](https://cloud.githubusercontent.com/assets/14239531/22624683/d3d279b4-eb2f-11e6-91f9-6705972434fd.png)
Kinda like how the back button lines up
![screenshot_20170204-153137](https://cloud.githubusercontent.com/assets/14239531/22624684/d3d65ab6-eb2f-11e6-8c62-ead30501e3c4.png)

**Comment by gauntface** [comment]
Thanks for the issue. I'll try and dig into this ASAP. Send like a pretty bad bug.

**Comment by bkazi** [comment]
Okay I did some digging since I've personally had this issue too and a possible hack seems to be adding `left: calc(100vw - 40px)` to `.page-nav-next` resolves the issue for reasons unbeknownst to me

* on Dev Tools emulation that is
![web-push-book gauntface com-chapter-03-01-permission-ux- nexus 5x](https://cloud.githubusercontent.com/assets/14239531/22624919/45ed21e2-eb9a-11e6-8f45-79ea08db822e.png)

**Comment by gauntface** [comment]
The problem was actually the images on that page where pushing out the viewport, this lead to the arrows being bumped out. Should be fixed once travis has built and deployed the changes.
