### ISSUE TITLE
Can't send push notification to multiple devices

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [gauntface/web-push-book#39]
I've deployed https://github.com/gauntface/web-push-book/tree/master/src/demos/node-server app to Heroku: https://limitless-lowlands-14011.herokuapp.com

I can't send push notification to multiple devices. Something strange happens.

I've opened deployed app in Chrome browser on my Nexus 5 smartphone and subscribed to notifications, pressed "Trigger push message" button on admin panel and received push notification on the smartphone. Subscriber list contained only 1 id. All is ok.

Then I've opened deployed app in Chrome browser on my desktop and subscribed to notifications, pressed "Trigger push message" button on admin panel (using desktop) and received push notification only on desktop. I have not received push notification on the smartphone. Subscriber list contained 2 ids. I've also tried to additionally test it by pressing "Trigger push message" button on admin panel, but on my smartphone, but still received push notification only on desktop.

After that I've opened deployed app in Chrome browser on my Nexus 9 tablet and subscribed to notifications, tried to press "Trigger push message" button on admin panel using desktop, smartphone and tablet, but still received push notification only on desktop. Subscriber list contained 3 ids.

Additionally I've tried to open deployed app in another Chrome browser instance on my desktop (Chrome Canary) and in Firefox browser on my desktop — the same result — still received push notification only in Chrome on desktop. Subscriber list contained 5 ids.

Why the app doesn't send push notifications to all subscribers?

**Comment by gauntface** [comment]
It is possible that there is a bug in the app. I'll go through and write some tests for the demo to see if there is anything I'm missing.

**Comment by gauntface** [comment]
Apologies for this and thanks for raising the issue.

Was a basic error on my part and should be fixed by: https://github.com/gauntface/web-push-book/commit/e5ac2f843c648fadcd97db3d715a1beffd2e2bfd
