### ISSUE TITLE
Firebase Cloud Messaging is not fully Web Push spec compliant

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [gauntface/web-push-book#40]
Firebase Cloud Messaging (SDK, not endpoint) _currently?_ is not fully Web Push spec compliant. It uses non-standard, e.g. `"click_action"` instead of `"actions"`, and doesn't support many standard, e.g. `"image"`, `"badge"`, `"sound"` and etc., keys for notification messages. See `Table 2c` on https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support page.

Please add info about it to https://github.com/gauntface/web-push-book/blob/master/src/_content/chapter-07/01-faq.md#firebase-has-a-javascript-sdk-what-and-why.

**Comment by gauntface** [comment]
The Firebase Cloud Messaging (FCM) SDK is not web push - I wrote some comments here: https://web-push-book.gauntface.com/chapter-07/01-faq/#firebase-has-a-javascript-sdk-what-and-why

Please open if you still have any questions and I'll update the FAQ.

**Comment by FluorescentHallucinogen** [comment]
In https://web-push-book.gauntface.com/chapter-07/01-faq/#firebase-has-a-javascript-sdk-what-and-why you wrote
> if you consider web push as just a browser and push service, then you can consider the Messaging SDK in Firebase as a library to try and simplify implementing web push

Using FCM SDK not only simplifies implementing web push, but add significant limitations.

On my work I've used https://github.com/firebase/quickstart-js/blob/master/messaging sample as starting point, but found that FCM SDK doesn't support `"image"` and `"actions"` keys for notification messages, that are important for current production project, and I switched to https://github.com/gauntface/web-push-book/tree/master/src/demos/node-server sample as starting point, but paid time has been spent. :) That's why I think you should add info about this limitations to the book.

**Comment by gauntface** [comment]
The notifications payload in FCM doesn't, but you can just send data and then you'll get a callback in onBackgroundMessage() and you can generate any notification you like. I.e. rather than send

```
{
  "notification": {
    "title": "Hello",
    "body": "World!"
  }
}
```

Send:

```
{
  "data": {
    "title": "Hello",
    "body": "World!"
  }
}
```

and add a custom listener in your service worker:

```
messaging.setBackgroundMessageHandler(function(payload) {
  return self.registration.showNotification(payload.title,
      {
        body: payload.body
      });
});

**Comment by FluorescentHallucinogen** [comment]
Thanks for the workaround!

**Comment by nimitbhargava** [comment]
@gauntface Instead of `payload.body` shouldn't it be `payload.notification.body`?
