### ISSUE TITLE
Must subscribers list be kept secret?

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [gauntface/web-push-book#44]
Must subscribers list really be kept secret?

See https://github.com/gauntface/web-push-book/blob/master/src/demos/node-server/index.js#L128-L129.

What can be done with items from subscribers list without private key?

**Comment by gauntface** [comment]
Yes it should be kept secret, publicly sharing it will be a big step in enabling a third parties to message your users.

**Comment by FluorescentHallucinogen** [comment]
Is it possible to send messages to subscriber without private key?

**Comment by gauntface** [comment]
No - but if your private key is discovered some how, the following step of getting your subscribe list to actually use it isn't a step since you've made it public.

**Comment by FluorescentHallucinogen** [comment]
Do I understand correctly that there are 3 types of notifications: 1. push without payload, 2. push with unencrypted (plain) payload, 3. push with encrypted payload (VAPID)?

Is it possible to send 1 and 2 without private key?

**Comment by FluorescentHallucinogen** [comment]
In https://web-push-book.gauntface.com/chapter-07/01-faq/#firebase-has-a-javascript-sdk-what-and-why you wrote

> you can use the proprietary FCM API to trigger push messages. This API doesn’t require encrypting payloads, you can send plain payload in a POST request body.

Is it possible to send push with unencrypted (plain) payload without FCM (e.g. using https://github.com/web-push-libs/web-push)?

**Comment by FluorescentHallucinogen** [comment]
What if the subscribers browsers do not support VAPID? Should I care about it and send them push only with unencrypted (plain) payload? How to detect VAPID support in browser?

**Comment by gauntface** [comment]
No payload support: https://web-push-book.gauntface.com/chapter-06/01-non-standards-browsers/#no-payload

> Is it possible to send push with unencrypted (plain) payload without FCM

No - That's why FCM has an SDK which supports it's proprietary FCM API. I would consider Web Push and FCM's SDK as entirely seperate things.
