### ISSUE TITLE
Add info about how to run/develop their own web push server/endpoint

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [gauntface/web-push-book#73]
Add info about web push server/endpoint architecture (e.g. https://mozilla-push-service.readthedocs.io) and open source projects (e.g. https://autopush.readthedocs.io, https://github.com/mozilla-services/autopush) for all who want to run/develop their own web push server/endpoint.

**Comment by gauntface** [comment]
This is outside of the scope for this book, but if you write up or see anyone write up a blog post on how to run, develop and get a browser to use the local push service, I'll be happy to link to it.
